<!-- Site footer -->
    <footer class="footer">
        <div class= "row">
            <div class="col-md-4 text-left">
                    <h3>Contact Us</h3>
                    Copyright © 2016–
                    <a href="http://www.rochester.edu/">University of Rochester</a>
                    |
                    <a href="http://www.rochester.edu/college/">AS&amp;E</a>
                    |
                    <a href="index.html">CSC</a>
                    <br>
                    <a href="http://www.rochester.edu/accessibility.html">Accessibility</a>
                    |
                    <a href="http://text.rochester.edu/tt/referrer" title="Access a text-only version of this page.">Text</a>
                    |
                    <a href="http://www.rochester.edu/college/webcomm/" title="Get help with your AS&amp;E website.">Web Communications</a>
            </div><!--.col-md-4-->
            <div class="col-md-4 text-center">
                <h3>Around The Web</h3>
                  <center><a href="https://www.facebook.com/University.of.Rochester" class="btn btn-social-icon btn-facebook" onclick="_gaq.push(['_trackEvent', 'btn-social-icon', 'click', 'btn-md']);"><i class="fa fa-facebook"></i></a>
                <a href="https://twitter.com/UofR"  class="btn btn-social-icon btn-twitter" onclick="_gaq.push(['_trackEvent', 'btn-social-icon', 'click', 'btn-md']);"><i class="fa fa-twitter"></i></a>
                <a href="http://tech.rochester.edu/services/gmail/"  class="btn btn-social-icon btn-google" onclick="_gaq.push(['_trackEvent', 'btn-social-icon', 'click', 'btn-md']);"><i class="fa fa-google"></i></a>
                <a href="https://www.linkedin.com/company/university-of-rochester" class="btn btn-social-icon btn-linkedin" onclick="_gaq.push(['_trackEvent', 'btn-social-icon', 'click', 'btn-md']);"><i class="fa fa-linkedin"></i></a>
                <a href="https://www.instagram.com/uradmissions/" class="btn btn-social-icon btn-instagram" onclick="_gaq.push(['_trackEvent', 'btn-social-icon', 'click', 'btn-md']);"><i class="fa fa-instagram"></i></a></center>
            </div>
            <div class= "col-md-4 text-right">
                <h3>Location</h3>
                <p>Department of Computer Science</p>
                <p>University of Rochester</p>
                <p>734 Computer Studies Building</p>
                <p>P.O. Box 270226</p>
                <p>Rochester, NY 14627</p>

                <p>(585) 275-5671</p>
            </div><!--.col-md-4-->
        </div><!--.row-->
    </footer>