<nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <!-- logo space <a class="navbar-brand" href="#">Project name</a> -->
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="https://www.cs.rochester.edu/about/index.html">About Us</a></li>
              <li><a href="https://www.cs.rochester.edu/research/index.html">Research</a></li>
              <li><a href="https://www.cs.rochester.edu/news-events/events/index.php">Gallery</a></li>
              <li><a href="https://www.cs.rochester.edu/undergraduate/index.html">Student Resources</a></li>
              <li><a href="https://enrollment.rochester.edu/apply/">Future Students</a></li>
              <li><a href="https://www.cs.rochester.edu/about/contact.html">Contact Us</a></li>
            </ul>

                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">Go!</button>
                    </span>
                </div>

          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>