        <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="#">Home</a></li>
              <li><a href="html/majors.html">Majors</a></li>
              <li><a href="html/minors.html">Minors</a></li>
              <li><a href="html/graduates.html">Graduate Studies</a></li>
              <li><a href="html/colophon.html">Colophon</a></li>
           </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>