 <!-- Static navbar -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation">
            <div class="container-fluid">
              <div class="navbar-header">

            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
              </div>
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav">
                    <li><a href="index.php">Home</a></li>
                    <li><a href="majors.php">Majors</a></li>
                    <li><a href="minors.php">Minors</a></li>
                    <li><a href="graduate.php">Graduate Studies</a></li>
                    <li><a href="colophon.php">Colophon</a></li>
                </ul>
                </div>    <!-- Collect the nav links, forms, and other content for toggling -->
            </div>
        </nav>